// <auto-generated />
namespace LTM.Teste.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tipodadoscolunaarquivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipodadoscolunaarquivo));
        
        string IMigrationMetadata.Id
        {
            get { return "201903312006428_tipodadoscolunaarquivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
